// ─── BJJ Game Data Definitions ──────────────────────────────────────────────
// All positions, techniques, tokens, and matchup tables for the prototype.

// ─── Token Types ────────────────────────────────────────────────────────────
export const TOKEN_TYPES = {
  posture_broken:       { id: 'posture_broken',       name: 'Posture Broken',       icon: '🔻' },
  inside_position:      { id: 'inside_position',      name: 'Inside Position',      icon: '🔲' },
  arm_isolated:         { id: 'arm_isolated',         name: 'Arm Isolated',         icon: '💪' },
  leg_isolated:         { id: 'leg_isolated',         name: 'Leg Isolated',         icon: '🦵' },
  balance_compromised:  { id: 'balance_compromised',  name: 'Balance Compromised',  icon: '⚖️' },
};

// ─── Action Categories ──────────────────────────────────────────────────────
export const CATEGORIES = {
  attack:   { id: 'attack',   name: 'Attack',   icon: '⚔️', hint: 'Submit or advance' },
  control:  { id: 'control',  name: 'Control',  icon: '🛡️', hint: 'Maintain & pressure' },
  defense:  { id: 'defense',  name: 'Defense',  icon: '🔒', hint: 'Protect & survive' },
  reversal: { id: 'reversal', name: 'Reversal', icon: '🔄', hint: 'Escape & reverse' },
};

// ─── Matchup Table (winner category → loser category → modifier) ────────────
// Attack > Control > Reversal > Defense > Attack  (each beats next by +1)
// Reduced from +/-2 to +/-1 so wrong guesses aren't devastating
export const MATCHUPS = {
  attack:   { attack: 0, control:  1, defense: -1, reversal:  0 },
  control:  { attack: -1, control: 0, defense:  0, reversal:  1 },
  defense:  { attack:  1, control: 0, defense:  0, reversal: -1 },
  reversal: { attack:  0, control: -1, defense: 1, reversal:  0 },
};

// ─── Positions ──────────────────────────────────────────────────────────────
export const POSITIONS = {
  standing_neutral: {
    id: 'standing_neutral',
    name: 'Standing Neutral',
    advantage: 0,
    initiative: 'neutral',
    topActions:    ['attack', 'control', 'defense'],
    bottomActions: ['attack', 'control', 'defense'],
    autoClearTokens: ['balance_compromised'],
    description: 'Both fighters standing, no dominant grip or position.',
  },
  closed_guard: {
    id: 'closed_guard',
    name: 'Closed Guard',
    advantage: 0,
    initiative: 'bottom',
    topActions:    ['attack', 'control', 'defense'],
    bottomActions: ['attack', 'control', 'reversal'],
    autoClearTokens: [],
    description: 'Bottom player has legs wrapped around top player.',
  },
  open_guard: {
    id: 'open_guard',
    name: 'Open Guard',
    advantage: 0,
    initiative: 'bottom',
    topActions:    ['attack', 'control'],
    bottomActions: ['attack', 'control', 'defense', 'reversal'],
    autoClearTokens: [],
    description: 'Bottom player using feet and grips to control distance.',
  },
  half_guard: {
    id: 'half_guard',
    name: 'Half Guard',
    advantage: 1,
    initiative: 'top',
    topActions:    ['attack', 'control'],
    bottomActions: ['defense', 'reversal', 'control'],
    autoClearTokens: [],
    description: 'Bottom player trapping one of top player\'s legs.',
  },
  side_control: {
    id: 'side_control',
    name: 'Side Control',
    advantage: 1,
    initiative: 'top',
    topActions:    ['attack', 'control'],
    bottomActions: ['defense', 'reversal'],
    autoClearTokens: ['balance_compromised'],
    description: 'Top player pinning from the side, chest-to-chest.',
  },
  mount: {
    id: 'mount',
    name: 'Mount',
    advantage: 2,
    initiative: 'top',
    topActions:    ['attack', 'control'],
    bottomActions: ['defense', 'reversal'],
    autoClearTokens: ['balance_compromised'],
    description: 'Top player sitting on bottom player\'s torso.',
  },
  back_control: {
    id: 'back_control',
    name: 'Back Control',
    advantage: 2,
    initiative: 'top',
    topActions:    ['attack', 'control'],
    bottomActions: ['defense', 'reversal'],
    autoClearTokens: ['balance_compromised', 'inside_position'],
    description: 'Behind the opponent with hooks or body triangle.',
  },
  turtle: {
    id: 'turtle',
    name: 'Turtle',
    advantage: 1,
    initiative: 'top',
    topActions:    ['attack', 'control'],
    bottomActions: ['defense', 'reversal'],
    autoClearTokens: ['posture_broken'],
    description: 'Bottom player balled up on hands and knees.',
  },
  front_headlock: {
    id: 'front_headlock',
    name: 'Front Headlock',
    advantage: 1,
    initiative: 'top',
    topActions:    ['attack', 'control'],
    bottomActions: ['defense', 'reversal'],
    autoClearTokens: [],
    description: 'Top player controlling the head from the front.',
  },
  knee_shield: {
    id: 'knee_shield',
    name: 'Knee Shield Half Guard',
    advantage: 0,
    initiative: 'bottom',
    topActions:    ['attack', 'control'],
    bottomActions: ['attack', 'defense', 'reversal', 'control'],
    autoClearTokens: [],
    description: 'Half guard variant with knee frame creating distance.',
  },
};

// ─── Techniques ─────────────────────────────────────────────────────────────
// Each technique lists which positions + roles it's available from.
// role: 'top' or 'bottom' (relative to the position's initiative)
// transition: if present, { position, userBecomesTop } on success
// isSubmission: true if this can end the match on dominant win

export const TECHNIQUES = [
  // ═══ ATTACK ═══════════════════════════════════════════════════════════════
  {
    id: 'takedown',
    name: 'Takedown',
    category: 'attack',
    availableFrom: [
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'side_control', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'guard_pull',
    name: 'Guard Pull',
    category: 'attack',
    availableFrom: [
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
    ],
    modifier: 0,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'closed_guard', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'knee_cut_pass',
    name: 'Knee Cut Pass',
    category: 'attack',
    availableFrom: [
      { position: 'open_guard', role: 'top' },
      { position: 'knee_shield', role: 'top' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'side_control', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'torreando_pass',
    name: 'Toreando Pass',
    category: 'attack',
    availableFrom: [
      { position: 'open_guard', role: 'top' },
    ],
    modifier: 1,
    risk: 'risky',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'side_control', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'mount_transition',
    name: 'Mount Transition',
    category: 'attack',
    availableFrom: [
      { position: 'side_control', role: 'top' },
      { position: 'half_guard', role: 'top' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'mount', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'back_take',
    name: 'Back Take',
    category: 'attack',
    availableFrom: [
      { position: 'mount', role: 'top' },
      { position: 'turtle', role: 'top' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'back_control', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'americana',
    name: 'Americana',
    category: 'attack',
    availableFrom: [
      { position: 'side_control', role: 'top' },
      { position: 'mount', role: 'top' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: ['arm_isolated'],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'kimura',
    name: 'Kimura',
    category: 'attack',
    availableFrom: [
      { position: 'side_control', role: 'top' },
      { position: 'closed_guard', role: 'bottom' },
      { position: 'half_guard', role: 'top' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'cross_collar_choke',
    name: 'Cross Collar Choke',
    category: 'attack',
    availableFrom: [
      { position: 'mount', role: 'top' },
      { position: 'closed_guard', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: ['posture_broken'],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'rear_naked_choke',
    name: 'Rear Naked Choke',
    category: 'attack',
    availableFrom: [
      { position: 'back_control', role: 'top' },
    ],
    modifier: 3,
    risk: 'neutral',
    requiredTokens: ['posture_broken'],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'armbar',
    name: 'Armbar',
    category: 'attack',
    availableFrom: [
      { position: 'mount', role: 'top' },
      { position: 'closed_guard', role: 'bottom' },
      { position: 'back_control', role: 'top' },
    ],
    modifier: 2,
    risk: 'risky',
    requiredTokens: ['arm_isolated'],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'triangle',
    name: 'Triangle Choke',
    category: 'attack',
    availableFrom: [
      { position: 'closed_guard', role: 'bottom' },
      { position: 'open_guard', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'risky',
    requiredTokens: ['posture_broken'],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'guillotine',
    name: 'Guillotine',
    category: 'attack',
    availableFrom: [
      { position: 'front_headlock', role: 'top' },
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
      { position: 'closed_guard', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'risky',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'darce_choke',
    name: "D'Arce Choke",
    category: 'attack',
    availableFrom: [
      { position: 'front_headlock', role: 'top' },
      { position: 'side_control', role: 'top' },
    ],
    modifier: 2,
    risk: 'risky',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'ezekiel_choke',
    name: 'Ezekiel Choke',
    category: 'attack',
    availableFrom: [
      { position: 'mount', role: 'top' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },
  {
    id: 'ankle_lock',
    name: 'Ankle Lock',
    category: 'attack',
    availableFrom: [
      { position: 'open_guard', role: 'bottom' },
      { position: 'open_guard', role: 'top' },
    ],
    modifier: 1,
    risk: 'risky',
    requiredTokens: ['leg_isolated'],
    tokenReward: null,
    transition: null,
    isSubmission: true,
  },

  // ═══ CONTROL ══════════════════════════════════════════════════════════════
  {
    id: 'crossface',
    name: 'Crossface',
    category: 'control',
    availableFrom: [
      { position: 'side_control', role: 'top' },
      { position: 'half_guard', role: 'top' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'chest_pressure',
    name: 'Chest Pressure',
    category: 'control',
    availableFrom: [
      { position: 'mount', role: 'top' },
      { position: 'side_control', role: 'top' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'seatbelt_grip',
    name: 'Seatbelt Grip',
    category: 'control',
    availableFrom: [
      { position: 'back_control', role: 'top' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'head_control',
    name: 'Head Control',
    category: 'control',
    availableFrom: [
      { position: 'front_headlock', role: 'top' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'collar_tie',
    name: 'Collar Tie',
    category: 'control',
    availableFrom: [
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'posture_break',
    name: 'Posture Break',
    category: 'control',
    availableFrom: [
      { position: 'closed_guard', role: 'bottom' },
      { position: 'open_guard', role: 'bottom' },
      { position: 'closed_guard', role: 'top' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: 'posture_broken',
    transition: null,
    isSubmission: false,
  },
  {
    id: 'underhook_control',
    name: 'Underhook',
    category: 'control',
    availableFrom: [
      { position: 'half_guard', role: 'bottom' },
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
      { position: 'knee_shield', role: 'bottom' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: 'inside_position',
    transition: null,
    isSubmission: false,
  },
  {
    id: 'wrist_control',
    name: 'Wrist Control',
    category: 'control',
    availableFrom: [
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
      { position: 'closed_guard', role: 'top' },
      { position: 'closed_guard', role: 'bottom' },
      { position: 'open_guard', role: 'top' },
      { position: 'open_guard', role: 'bottom' },
      { position: 'mount', role: 'top' },
      { position: 'side_control', role: 'top' },
      { position: 'half_guard', role: 'top' },
      { position: 'back_control', role: 'top' },
      { position: 'knee_shield', role: 'bottom' },
    ],
    modifier: 0,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: 'arm_isolated',
    transition: null,
    isSubmission: false,
  },
  {
    id: 'leg_lace',
    name: 'Leg Entangle',
    category: 'control',
    availableFrom: [
      { position: 'open_guard', role: 'top' },
      { position: 'open_guard', role: 'bottom' },
      { position: 'half_guard', role: 'bottom' },
      { position: 'knee_shield', role: 'bottom' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: 'leg_isolated',
    transition: null,
    isSubmission: false,
  },
  {
    id: 'knee_shield_frame',
    name: 'Knee Shield',
    category: 'control',
    availableFrom: [
      { position: 'knee_shield', role: 'bottom' },
      { position: 'half_guard', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'body_lock',
    name: 'Body Lock',
    category: 'control',
    availableFrom: [
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
      { position: 'back_control', role: 'top' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: 'balance_compromised',
    transition: null,
    isSubmission: false,
  },

  // ═══ DEFENSE ══════════════════════════════════════════════════════════════
  {
    id: 'frame_and_shrimp',
    name: 'Frame & Shrimp',
    category: 'defense',
    availableFrom: [
      { position: 'side_control', role: 'bottom' },
      { position: 'mount', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'guard_recovery',
    name: 'Guard Recovery',
    category: 'defense',
    availableFrom: [
      { position: 'side_control', role: 'bottom' },
      { position: 'half_guard', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'closed_guard', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'posture_up',
    name: 'Posture Up',
    category: 'defense',
    availableFrom: [
      { position: 'closed_guard', role: 'top' },
      { position: 'open_guard', role: 'top' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    tokenRemove: 'posture_broken',
    transition: null,
    isSubmission: false,
  },
  {
    id: 'hand_fighting',
    name: 'Hand Fighting',
    category: 'defense',
    availableFrom: [
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
      { position: 'closed_guard', role: 'top' },
      { position: 'closed_guard', role: 'bottom' },
      { position: 'open_guard', role: 'top' },
      { position: 'open_guard', role: 'bottom' },
      { position: 'side_control', role: 'bottom' },
      { position: 'mount', role: 'bottom' },
      { position: 'back_control', role: 'bottom' },
      { position: 'knee_shield', role: 'bottom' },
    ],
    modifier: 0,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    tokenRemove: 'arm_isolated',
    transition: null,
    isSubmission: false,
  },
  {
    id: 'bridge',
    name: 'Bridge',
    category: 'defense',
    availableFrom: [
      { position: 'mount', role: 'bottom' },
      { position: 'side_control', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'turtle_up',
    name: 'Turtle Up',
    category: 'defense',
    availableFrom: [
      { position: 'side_control', role: 'bottom' },
      { position: 'mount', role: 'bottom' },
      { position: 'back_control', role: 'bottom' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'turtle', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'sprawl',
    name: 'Sprawl',
    category: 'defense',
    availableFrom: [
      { position: 'standing_neutral', role: 'top' },
      { position: 'standing_neutral', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },
  {
    id: 'shell_guard',
    name: 'Shell Guard',
    category: 'defense',
    availableFrom: [
      { position: 'mount', role: 'bottom' },
      { position: 'back_control', role: 'bottom' },
      { position: 'side_control', role: 'bottom' },
      { position: 'front_headlock', role: 'bottom' },
      { position: 'turtle', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: null,
    isSubmission: false,
  },

  // ═══ REVERSAL ═════════════════════════════════════════════════════════════
  {
    id: 'scissor_sweep',
    name: 'Scissor Sweep',
    category: 'reversal',
    availableFrom: [
      { position: 'closed_guard', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'mount', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'hip_bump_sweep',
    name: 'Hip Bump Sweep',
    category: 'reversal',
    availableFrom: [
      { position: 'closed_guard', role: 'bottom' },
    ],
    modifier: 3,
    risk: 'risky',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'mount', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'elbow_escape',
    name: 'Elbow Escape',
    category: 'reversal',
    availableFrom: [
      { position: 'mount', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'half_guard', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'trap_and_roll',
    name: 'Trap & Roll',
    category: 'reversal',
    availableFrom: [
      { position: 'mount', role: 'bottom' },
    ],
    modifier: 3,
    risk: 'neutral',
    requiredTokens: ['arm_isolated'],
    tokenReward: null,
    transition: { position: 'closed_guard', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'granby_roll',
    name: 'Granby Roll',
    category: 'reversal',
    availableFrom: [
      { position: 'turtle', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'closed_guard', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'technical_standup',
    name: 'Technical Standup',
    category: 'reversal',
    availableFrom: [
      { position: 'open_guard', role: 'bottom' },
      { position: 'closed_guard', role: 'bottom' },
      { position: 'knee_shield', role: 'bottom' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'standing_neutral', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'back_escape',
    name: 'Back Escape',
    category: 'reversal',
    availableFrom: [
      { position: 'back_control', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'half_guard', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'old_school_sweep',
    name: 'Old School Sweep',
    category: 'reversal',
    availableFrom: [
      { position: 'half_guard', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: ['inside_position'],
    tokenReward: null,
    transition: { position: 'side_control', userBecomesTop: true },
    isSubmission: false,
  },
  {
    id: 'sit_out',
    name: 'Sit Out',
    category: 'reversal',
    availableFrom: [
      { position: 'turtle', role: 'bottom' },
      { position: 'front_headlock', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'risky',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'standing_neutral', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'knee_shield_recover',
    name: 'Reguard to Knee Shield',
    category: 'reversal',
    availableFrom: [
      { position: 'side_control', role: 'bottom' },
      { position: 'half_guard', role: 'bottom' },
    ],
    modifier: 1,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'knee_shield', userBecomesTop: false },
    isSubmission: false,
  },
  {
    id: 'headlock_escape',
    name: 'Duck Under',
    category: 'reversal',
    availableFrom: [
      { position: 'front_headlock', role: 'bottom' },
    ],
    modifier: 2,
    risk: 'neutral',
    requiredTokens: [],
    tokenReward: null,
    transition: { position: 'back_control', userBecomesTop: true },
    isSubmission: false,
  },
];

// ─── Helper Functions ───────────────────────────────────────────────────────

/**
 * Get all techniques available for a given position and role.
 */
export function getTechniquesForPositionRole(positionId, role, category = null) {
  return TECHNIQUES.filter(t => {
    const posMatch = t.availableFrom.some(
      af => af.position === positionId && af.role === role
    );
    if (!posMatch) return false;
    if (category && t.category !== category) return false;
    return true;
  });
}

/**
 * Check if a technique's token requirements are met.
 */
export function canUseTechnique(technique, playerTokens) {
  if (!technique.requiredTokens || technique.requiredTokens.length === 0) return true;
  return technique.requiredTokens.every(req => playerTokens.includes(req));
}

/**
 * Get available categories for a position and role.
 */
export function getAvailableCategories(positionId, role) {
  const pos = POSITIONS[positionId];
  if (!pos) return [];
  return role === 'top' ? pos.topActions : pos.bottomActions;
}

/**
 * Get the matchup modifier for player's category vs opponent's category.
 */
export function getMatchupModifier(playerCategory, opponentCategory) {
  return MATCHUPS[playerCategory]?.[opponentCategory] ?? 0;
}
